version: 2

sources:
  - name: morbidite_h
    schema: morbidite_h
    tables:
      - name: taux_recours3
        identifier: tableau_3_ren
        description: "test"
      - name: duree_sejours2
        identifier: tableau_2_ren
        description: "test"
      - name: nombre_hospit1
        identifier: tableau_1_ren
        description: 'test'

      - name: class_services
        identifier: Classification_MCO_PSY_ESND_SRR
        description: 'test'

  - name: pop_departement
    schema: pop_departement
    tables:
      - name: population_departement
        identifier: population_departement
        description: 'test'
      - name: population_region
        identifier: population_region
        description: 'test'


  - name: capacite_services_h
    schema: capacite_services_h
    tables:
      - name: capacite_2022_par_service_clean
        identifier: capacite_2022_par_service_clean
        description: "Tebrfbest"
      - name: capacite_2022_par_etablissement_clean
        identifier: capacite_2022_par_etablissement_clean
        description: "Test"
      - name: capacite_services_dpt_region
        identifier: capacite_services_dpt_region
        description: 'test'

