version: 2

sources:
  - name: morbidite_h
    schema: morbidite_h
    tables:
      - name: taux_recours
        identifier: tranche_age_intermediate
        description: "test"

models:
  - name: stg_nombre_morbidites
    description: ""

  - name: stg_duree_sejours
    description: ""

  - name: stg_taux_recours
    description: ""
