version: 2

sources:
  - name: morbidite_h
    schema: morbidite_h
    tables:
      - name: taux_recours
        identifier: tranche_age_hospi_clean
        description: "test"
      - name: duree_sejours
        identifier: duree_hospi_clean
        description: "test"
      - name: nombre_hospit
        identifier: nbr_hospi_clean
        description: 'test'


