version: 2

sources:
  - name: morbidite_h
    schema: morbidite_h
    tables:
      - name: nombre_morbidites
        identifier: tableau_1
        description: ""
      - name: duree_sejours
        identifier: tableau_2
        description: ""
      - name: taux_recours
        identifier: tableau_3
        description: ""

models:
  - name: stg_nombre_morbidites
    description: ""

  - name: stg_duree_sejours
    description: ""

  - name: stg_taux_recours
    description: ""
